server {
    listen 3000;
    server_name localhost;
    client_max_body_size 200M;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}