build:backend:
  stage: build
  image:
    name: $CI_REGISTRY_IMAGE/kaniko:latest
    entrypoint: [""]
  parallel:
    matrix:
      - SERVICE_NAME: [backend, pipeline]
  before_script:
    - mkdir -p "$CI_PROJECT_DIR/.docker"
    - |
      cat > "$CI_PROJECT_DIR/.docker/config.json" <<JSON
      {"auths": {"${CI_REGISTRY}": {"username": "${CI_REGISTRY_USER}", "password": "${CI_REGISTRY_PASSWORD}"}}}
      JSON
  script:
    - |
      /kaniko/executor
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/$SERVICE_NAME/Dockerfile
        --destination $CI_REGISTRY_IMAGE/$SERVICE_NAME:$CI_COMMIT_TAG
        --cache=true
        --cache-repo=$CI_REGISTRY_IMAGE/kaniko-cache
        --cache-ttl=168h
  rules:
    - if: "$CI_COMMIT_TAG"

build:frontend:
  stage: build
  image: $CI_REGISTRY_IMAGE/node:20-alpine
  script:
    - cd frontend
    - npm ci
    - npm run build
  rules:
    - if: "$CI_COMMIT_TAG"
      when: always
    - if: $CI_COMMIT_BRANCH == "ci-test"
      when: always